FROM iron/go

RUN apk update && \
    apk add  --no-cache --virtual .build-deps ca-certificates

RUN apk add librdkafka-dev  --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted

RUN apk add musl libressl2.5-libcrypto libressl2.5-libssl && \
    apk add cyrus-sasl lz4-dev

#RUN apk add krb5 sqlite openssl pkgconf 

RUN rm -rf /var/cache/apk/*
