version: '3'
services:

  # zookeeper starts first
  zk1:
    image: ${MYHUB}/confluentinc/cp-zookeeper:3.3.0
    networks:
        - kafka-net
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
    ports:
        - "22181:22181"

  kafka1:
    image: ${MYHUB}/confluentinc/cp-kafka:3.3.0
    networks:
        - kafka-net
    depends_on:
        - zk1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
    kafka-net:
        external: true
